/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SalesOrdersRouteImport } from './routes/sales-orders'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DiscountsRouteImport } from './routes/discounts'
import { Route as DiscountRecipientsRouteImport } from './routes/discount-recipients'
import { Route as DiscountDebtsRouteImport } from './routes/discount-debts'
import { Route as DiscountCalculationsRouteImport } from './routes/discount-calculations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as AdminUsersRouteImport } from './routes/admin-users'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSystemRestoreRouteImport } from './routes/api/system/restore'
import { Route as ApiSystemBackupsRouteImport } from './routes/api/system/backups'
import { Route as ApiSystemBackupRouteImport } from './routes/api/system/backup'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOrdersRoute = SalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsRoute = DiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountRecipientsRoute = DiscountRecipientsRouteImport.update({
  id: '/discount-recipients',
  path: '/discount-recipients',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountDebtsRoute = DiscountDebtsRouteImport.update({
  id: '/discount-debts',
  path: '/discount-debts',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountCalculationsRoute = DiscountCalculationsRouteImport.update({
  id: '/discount-calculations',
  path: '/discount-calculations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemRestoreRoute = ApiSystemRestoreRouteImport.update({
  id: '/api/system/restore',
  path: '/api/system/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemBackupsRoute = ApiSystemBackupsRouteImport.update({
  id: '/api/system/backups',
  path: '/api/system/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemBackupRoute = ApiSystemBackupRouteImport.update({
  id: '/api/system/backup',
  path: '/api/system/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-users': typeof AdminUsersRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/discount-calculations': typeof DiscountCalculationsRoute
  '/discount-debts': typeof DiscountDebtsRoute
  '/discount-recipients': typeof DiscountRecipientsRoute
  '/discounts': typeof DiscountsRoute
  '/employees': typeof EmployeesRoute
  '/inventory': typeof InventoryRoute
  '/products': typeof ProductsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/suppliers': typeof SuppliersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/system/backup': typeof ApiSystemBackupRoute
  '/api/system/backups': typeof ApiSystemBackupsRoute
  '/api/system/restore': typeof ApiSystemRestoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-users': typeof AdminUsersRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/discount-calculations': typeof DiscountCalculationsRoute
  '/discount-debts': typeof DiscountDebtsRoute
  '/discount-recipients': typeof DiscountRecipientsRoute
  '/discounts': typeof DiscountsRoute
  '/employees': typeof EmployeesRoute
  '/inventory': typeof InventoryRoute
  '/products': typeof ProductsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/suppliers': typeof SuppliersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/system/backup': typeof ApiSystemBackupRoute
  '/api/system/backups': typeof ApiSystemBackupsRoute
  '/api/system/restore': typeof ApiSystemRestoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-users': typeof AdminUsersRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/discount-calculations': typeof DiscountCalculationsRoute
  '/discount-debts': typeof DiscountDebtsRoute
  '/discount-recipients': typeof DiscountRecipientsRoute
  '/discounts': typeof DiscountsRoute
  '/employees': typeof EmployeesRoute
  '/inventory': typeof InventoryRoute
  '/products': typeof ProductsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/suppliers': typeof SuppliersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/system/backup': typeof ApiSystemBackupRoute
  '/api/system/backups': typeof ApiSystemBackupsRoute
  '/api/system/restore': typeof ApiSystemRestoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-users'
    | '/customers'
    | '/dashboard'
    | '/discount-calculations'
    | '/discount-debts'
    | '/discount-recipients'
    | '/discounts'
    | '/employees'
    | '/inventory'
    | '/products'
    | '/purchase-orders'
    | '/reports'
    | '/sales-orders'
    | '/suppliers'
    | '/api/auth/$'
    | '/api/system/backup'
    | '/api/system/backups'
    | '/api/system/restore'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-users'
    | '/customers'
    | '/dashboard'
    | '/discount-calculations'
    | '/discount-debts'
    | '/discount-recipients'
    | '/discounts'
    | '/employees'
    | '/inventory'
    | '/products'
    | '/purchase-orders'
    | '/reports'
    | '/sales-orders'
    | '/suppliers'
    | '/api/auth/$'
    | '/api/system/backup'
    | '/api/system/backups'
    | '/api/system/restore'
  id:
    | '__root__'
    | '/'
    | '/admin-users'
    | '/customers'
    | '/dashboard'
    | '/discount-calculations'
    | '/discount-debts'
    | '/discount-recipients'
    | '/discounts'
    | '/employees'
    | '/inventory'
    | '/products'
    | '/purchase-orders'
    | '/reports'
    | '/sales-orders'
    | '/suppliers'
    | '/api/auth/$'
    | '/api/system/backup'
    | '/api/system/backups'
    | '/api/system/restore'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DiscountCalculationsRoute: typeof DiscountCalculationsRoute
  DiscountDebtsRoute: typeof DiscountDebtsRoute
  DiscountRecipientsRoute: typeof DiscountRecipientsRoute
  DiscountsRoute: typeof DiscountsRoute
  EmployeesRoute: typeof EmployeesRoute
  InventoryRoute: typeof InventoryRoute
  ProductsRoute: typeof ProductsRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  ReportsRoute: typeof ReportsRoute
  SalesOrdersRoute: typeof SalesOrdersRoute
  SuppliersRoute: typeof SuppliersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSystemBackupRoute: typeof ApiSystemBackupRoute
  ApiSystemBackupsRoute: typeof ApiSystemBackupsRoute
  ApiSystemRestoreRoute: typeof ApiSystemRestoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-orders': {
      id: '/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof SalesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts': {
      id: '/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof DiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discount-recipients': {
      id: '/discount-recipients'
      path: '/discount-recipients'
      fullPath: '/discount-recipients'
      preLoaderRoute: typeof DiscountRecipientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discount-debts': {
      id: '/discount-debts'
      path: '/discount-debts'
      fullPath: '/discount-debts'
      preLoaderRoute: typeof DiscountDebtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discount-calculations': {
      id: '/discount-calculations'
      path: '/discount-calculations'
      fullPath: '/discount-calculations'
      preLoaderRoute: typeof DiscountCalculationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-users': {
      id: '/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/restore': {
      id: '/api/system/restore'
      path: '/api/system/restore'
      fullPath: '/api/system/restore'
      preLoaderRoute: typeof ApiSystemRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/backups': {
      id: '/api/system/backups'
      path: '/api/system/backups'
      fullPath: '/api/system/backups'
      preLoaderRoute: typeof ApiSystemBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/backup': {
      id: '/api/system/backup'
      path: '/api/system/backup'
      fullPath: '/api/system/backup'
      preLoaderRoute: typeof ApiSystemBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminUsersRoute: AdminUsersRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DiscountCalculationsRoute: DiscountCalculationsRoute,
  DiscountDebtsRoute: DiscountDebtsRoute,
  DiscountRecipientsRoute: DiscountRecipientsRoute,
  DiscountsRoute: DiscountsRoute,
  EmployeesRoute: EmployeesRoute,
  InventoryRoute: InventoryRoute,
  ProductsRoute: ProductsRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  ReportsRoute: ReportsRoute,
  SalesOrdersRoute: SalesOrdersRoute,
  SuppliersRoute: SuppliersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSystemBackupRoute: ApiSystemBackupRoute,
  ApiSystemBackupsRoute: ApiSystemBackupsRoute,
  ApiSystemRestoreRoute: ApiSystemRestoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
